name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # ou o branch que você estiver usando

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Adiciona a permissão necessária
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4

